import { Seeder, SeederFactoryManager } from "typeorm-extension";
import { DataSource } from "typeorm";
import { Product } from "../entities/Product.entity";
import { User } from "../entities/User.entity";

export class ProductSeed implements Seeder {
  public async run(
    dataSource: DataSource,
    factoryManager: SeederFactoryManager
  ): Promise<any> {
    const repository = dataSource.getRepository(Product);
    const userRepository = dataSource.getRepository(User);

    const UserTest = await userRepository.findOneBy({
      email: "user@example.com",
    });

    const products = [
      { name: "Camiseta", quantity: 993, user: UserTest },
      { name: "Calça jeans", quantity: 916, user: UserTest },
      { name: "Tênis", quantity: 104, user: UserTest },
      { name: "Mochila", quantity: 169, user: UserTest },
      { name: "Boné", quantity: 528, user: UserTest },
      { name: "Relógio", quantity: 291, user: UserTest },
      { name: "Celular", quantity: 679, user: UserTest },
      { name: "Laptop", quantity: 733, user: UserTest },
      { name: "Fone de ouvido", quantity: 972, user: UserTest },
      { name: "Cadeira de escritório", quantity: 425, user: UserTest },
      { name: "Bolsa", quantity: 965, user: UserTest },
      { name: "Livro", quantity: 918, user: UserTest },
      { name: "Óculos de sol", quantity: 120, user: UserTest },
      { name: "Câmera digital", quantity: 108, user: UserTest },
      { name: "Televisão", quantity: 949, user: UserTest },
      { name: "Impressora", quantity: 851, user: UserTest },
      { name: "Mouse", quantity: 628, user: UserTest },
      { name: "Teclado", quantity: 949, user: UserTest },
      { name: "Tablet", quantity: 202, user: UserTest },
      { name: "Chapéu", quantity: 32, user: UserTest },
      { name: "Bicicleta", quantity: 174, user: UserTest },
      { name: "Skate", quantity: 895, user: UserTest },
      { name: "Bola de futebol", quantity: 874, user: UserTest },
      { name: "Raquete de tênis", quantity: 242, user: UserTest },
      { name: "Batedeira", quantity: 974, user: UserTest },
      { name: "Liquidificador", quantity: 194, user: UserTest },
      { name: "Ferro de passar roupa", quantity: 289, user: UserTest },
      { name: "Aspirador de pó", quantity: 428, user: UserTest },
      { name: "Secador de cabelo", quantity: 907, user: UserTest },
      { name: "Cafeteira", quantity: 179, user: UserTest },
      { name: "Forno micro-ondas", quantity: 222, user: UserTest },
      { name: "Geladeira", quantity: 200, user: UserTest },
      { name: "Chinelo", quantity: 727, user: UserTest },
      { name: "Guarda-chuva", quantity: 255, user: UserTest },
      { name: "Caneta", quantity: 641, user: UserTest },
      { name: "Papel A4", quantity: 800, user: UserTest },
      { name: "Lápis de cor", quantity: 348, user: UserTest },
      { name: "Pasta de dente", quantity: 340, user: UserTest },
      { name: "Escova de dentes", quantity: 901, user: UserTest },
      { name: "Sabonete", quantity: 607, user: UserTest },
      { name: "Shampoo", quantity: 867, user: UserTest },
      { name: "Condicionador", quantity: 463, user: UserTest },
      { name: "Toalha de banho", quantity: 167, user: UserTest },
      { name: "Chuveiro elétrico", quantity: 585, user: UserTest },
      { name: "Ventilador", quantity: 75, user: UserTest },
      { name: "Ar condicionado", quantity: 80, user: UserTest },
      { name: "Mesa de jantar", quantity: 88, user: UserTest },
      { name: "Cadeira de praia", quantity: 211, user: UserTest },
      { name: "Guarda-sol", quantity: 966, user: UserTest },
      { name: "Barraca de camping", quantity: 772, user: UserTest },
      { name: "Fogão a gás", quantity: 629, user: UserTest },
      { name: "Panela de pressão", quantity: 959, user: UserTest },
      { name: "Prato", quantity: 623, user: UserTest },
      { name: "Garfo", quantity: 697, user: UserTest },
      { name: "Faca", quantity: 592, user: UserTest },
      { name: "Colher", quantity: 459, user: UserTest },
      { name: "Frigideira", quantity: 39, user: UserTest },
      { name: "Máquina de lavar roupa", quantity: 309, user: UserTest },
      { name: "Secadora de roupa", quantity: 672, user: UserTest },
      { name: "Máquina de café", quantity: 430, user: UserTest },
      { name: "Forno elétrico", quantity: 811, user: UserTest },
      { name: "Chaleira elétrica", quantity: 820, user: UserTest },
      { name: "Ventilador de teto", quantity: 102, user: UserTest },
      { name: "Cama de casal", quantity: 614, user: UserTest },
      { name: "Sofá", quantity: 683, user: UserTest },
      { name: "Poltrona", quantity: 528, user: UserTest },
      { name: "Mesa de centro", quantity: 187, user: UserTest },
      { name: "Tapete", quantity: 902, user: UserTest },
      { name: "Luminária de mesa", quantity: 527, user: UserTest },
      { name: "Abajur", quantity: 964, user: UserTest },
      { name: "DVD player", quantity: 934, user: UserTest },
      { name: "Blu-ray player", quantity: 485, user: UserTest },
      { name: "Caixa de som Bluetooth", quantity: 115, user: UserTest },
      { name: "Smartwatch", quantity: 3, user: UserTest },
      { name: "Impressora a laser", quantity: 606, user: UserTest },
      { name: "Scanner", quantity: 679, user: UserTest },
      { name: "Gravador de voz", quantity: 621, user: UserTest },
      { name: "Notebook", quantity: 14, user: UserTest },
      { name: "Mala de viagem", quantity: 983, user: UserTest },
      { name: "Bicicleta ergométrica", quantity: 520, user: UserTest },
      { name: "Esteira", quantity: 240, user: UserTest },
      { name: "Haltere", quantity: 855, user: UserTest },
      { name: "Bola de pilates", quantity: 42, user: UserTest },
      { name: "Fita métrica", quantity: 746, user: UserTest },
      { name: "Balança de banheiro", quantity: 348, user: UserTest },
      { name: "Escova de cabelo", quantity: 750, user: UserTest },
      { name: "Roteador Wi-Fi", quantity: 107, user: UserTest },
      { name: "Serra elétrica", quantity: 381, user: UserTest },
      { name: "Furadeira", quantity: 114, user: UserTest },
      { name: "Martelo", quantity: 911, user: UserTest },
      { name: "Chave de fenda", quantity: 836, user: UserTest },
      { name: "Chave inglesa", quantity: 21, user: UserTest },
      { name: "Escada", quantity: 888, user: UserTest },
      { name: "Carrinho de mão", quantity: 227, user: UserTest },
      { name: "Bomba de ar", quantity: 407, user: UserTest },
      { name: "Mangueira de jardim", quantity: 742, user: UserTest },
      { name: "Tenda de camping", quantity: 235, user: UserTest },
      { name: "Colchão de ar", quantity: 17, user: UserTest },
      { name: "Guarda-roupa", quantity: 564, user: UserTest },
      { name: "Cômoda", quantity: 420, user: UserTest },
      { name: "Criado-mudo", quantity: 392, user: UserTest },
      { name: "Aparador de grama", quantity: 340, user: UserTest },
      { name: "Fogão a lenha", quantity: 304, user: UserTest },
      { name: "Piano", quantity: 446, user: UserTest },
      { name: "Violão", quantity: 718, user: UserTest },
      { name: "Teclado musical", quantity: 680, user: UserTest },
      { name: "Microfone", quantity: 508, user: UserTest },
      {
        name: "Amplificador de guitarra",
        quantity: 109,
        user: UserTest,
      },
      { name: "Cadeira de balanço", quantity: 246, user: UserTest },
      { name: "Sapato social", quantity: 956, user: UserTest },
      { name: "Tênis de corrida", quantity: 436, user: UserTest },
      { name: "Botas", quantity: 243, user: UserTest },
      { name: "Sapato de salto alto", quantity: 223, user: UserTest },
      { name: "Sandália", quantity: 667, user: UserTest },
      { name: "Biquíni", quantity: 295, user: UserTest },
      { name: "Maiô", quantity: 742, user: UserTest },
      { name: "Óculos de natação", quantity: 736, user: UserTest },
      { name: "Prancha de surf", quantity: 13, user: UserTest },
      { name: "Luvas de boxe", quantity: 658, user: UserTest },
      { name: "Raquete de ping pong", quantity: 544, user: UserTest },
      { name: "Fralda descartável", quantity: 302, user: UserTest },
      { name: "Carrinho de bebê", quantity: 502, user: UserTest },
      {
        name: "Cadeirinha de carro para bebê",
        quantity: 82,
        user: UserTest,
      },
      { name: "Brinquedos para bebê", quantity: 820, user: UserTest },
      { name: "Trem de brinquedo", quantity: 282, user: UserTest },
      { name: "Boneca", quantity: 965, user: UserTest },
      { name: "Quebra-cabeça", quantity: 657, user: UserTest },
      { name: "Jogo de tabuleiro", quantity: 840, user: UserTest },
      { name: "Kit de maquiagem", quantity: 65, user: UserTest },
      { name: "Perfume", quantity: 371, user: UserTest },
      { name: "Colar", quantity: 259, user: UserTest },
      { name: "Brinco", quantity: 148, user: UserTest },
      { name: "Anel", quantity: 4, user: UserTest },
      { name: "Pulseira", quantity: 460, user: UserTest },
      { name: "Relógio de pulso", quantity: 564, user: UserTest },
      { name: "Chapinha de cabelo", quantity: 748, user: UserTest },
      { name: "Aparador de barba", quantity: 68, user: UserTest },
      { name: "Cortador de cabelo", quantity: 723, user: UserTest },
      { name: "Laptop gamer", quantity: 634, user: UserTest },
      { name: "Console de videogame", quantity: 767, user: UserTest },
      { name: "Controle remoto", quantity: 190, user: UserTest },
      { name: "Monitor de computador", quantity: 517, user: UserTest },
      { name: "Mesa de escritório", quantity: 849, user: UserTest },
      { name: "Livro de ficção", quantity: 388, user: UserTest },
      { name: "Livro de não ficção", quantity: 796, user: UserTest },
      { name: "DVD de filme", quantity: 181, user: UserTest },
      { name: "CD de música", quantity: 491, user: UserTest },
      { name: "Vinil de música", quantity: 975, user: UserTest },
      { name: "Câmera instantânea", quantity: 445, user: UserTest },
      { name: "Bolsa de câmera", quantity: 235, user: UserTest },
      { name: "Tripé", quantity: 252, user: UserTest },
      { name: "Tela de projeção", quantity: 649, user: UserTest },
      { name: "Projetor de vídeo", quantity: 458, user: UserTest },
      { name: "Micro-ondas", quantity: 139, user: UserTest },
      { name: "Frigobar", quantity: 185, user: UserTest },
      { name: "Panela elétrica", quantity: 382, user: UserTest },
      { name: "Mixer de mão", quantity: 514, user: UserTest },
      { name: "Grill elétrico", quantity: 339, user: UserTest },
      { name: "Aquecedor elétrico", quantity: 707, user: UserTest },
      { name: "Mesa de piquenique", quantity: 390, user: UserTest },
      { name: "Cadeira de camping", quantity: 320, user: UserTest },
      { name: "Saco de dormir", quantity: 139, user: UserTest },
      { name: "Isqueiro", quantity: 236, user: UserTest },
      { name: "Barraca de acampamento", quantity: 533, user: UserTest },
      { name: "Churrasqueira portátil", quantity: 425, user: UserTest },
      { name: "Skate elétrico", quantity: 194, user: UserTest },
      { name: "Hoverboard", quantity: 473, user: UserTest },
      { name: "Patins", quantity: 792, user: UserTest },
      { name: "Guarda-sol de praia", quantity: 998, user: UserTest },
      { name: "Cadeira de jardim", quantity: 56, user: UserTest },
      { name: "Estante", quantity: 547, user: UserTest },
      { name: "Máquina de costura", quantity: 683, user: UserTest },
      { name: "Violino", quantity: 358, user: UserTest },
      { name: "Acordeão", quantity: 539, user: UserTest },
      { name: "Trompete", quantity: 372, user: UserTest },
      { name: "Flauta", quantity: 542, user: UserTest },
      { name: "Tuba", quantity: 447, user: UserTest },
      { name: "Violoncelo", quantity: 214, user: UserTest },
      { name: "Piano elétrico", quantity: 335, user: UserTest },
      { name: "Bateria eletrônica", quantity: 466, user: UserTest },
      { name: "Violão clássico", quantity: 298, user: UserTest },
      { name: "Teclado eletrônico", quantity: 968, user: UserTest },
      { name: "Guitarra elétrica", quantity: 242, user: UserTest },
      { name: "Baixo elétrico", quantity: 643, user: UserTest },
      { name: "Saxofone", quantity: 215, user: UserTest },
      { name: "Clarinet", quantity: 253, user: UserTest },
      { name: "Gaita", quantity: 699, user: UserTest },
      { name: "Harpa", quantity: 282, user: UserTest },
      { name: "Óleo de motor", quantity: 843, user: UserTest },
      { name: "Bateria de carro", quantity: 545, user: UserTest },
      { name: "Pneus de carro", quantity: 438, user: UserTest },
      { name: "Ferramenta de pneu", quantity: 905, user: UserTest },
      { name: "Macaco hidráulico", quantity: 426, user: UserTest },
      { name: "Chave de roda", quantity: 575, user: UserTest },
      { name: "Caixa de ferramentas", quantity: 298, user: UserTest },
      { name: "Máquina de solda", quantity: 24, user: UserTest },
      { name: "Gerador de energia", quantity: 611, user: UserTest },
    ];

    const newProduct = await repository.create(products);
    await repository.save(newProduct);
  }
}
