import { Seeder, SeederFactoryManager } from "typeorm-extension";
import { DataSource } from "typeorm";
import { Product } from "../entities/Product.entity";
import { User } from "../entities/User.entity";

export class ProductSeed implements Seeder {
  public async run(
    dataSource: DataSource,
    factoryManager: SeederFactoryManager
  ): Promise<any> {
    const repository = dataSource.getRepository(Product);
    const userRepository = dataSource.getRepository(User);

    const UserTest = await userRepository.findOneBy({
      email: "user@example.com",
    });

    const products = [
      { name: "Creme de leite", quantity: 338, user: UserTest },
      {
        name: "Suco de abóbora orgânico",
        quantity: 581,
        user: UserTest,
      },
      {
        name: "Suco de cranberry orgânico",
        quantity: 952,
        user: UserTest,
      },
      { name: "Chocolate com amêndoas", quantity: 785, user: UserTest },
      { name: "Suco de acerola light", quantity: 187, user: UserTest },
      { name: "Chocolate ao leite", quantity: 969, user: UserTest },
      { name: "Pera", quantity: 894, user: UserTest },
      { name: "Feijão", quantity: 802, user: UserTest },
      { name: "Suco de goiaba", quantity: 563, user: UserTest },
      {
        name: "Suco de tamarindo orgânico",
        quantity: 629,
        user: UserTest,
      },
      {
        name: "Suco de abóbora orgânico",
        quantity: 720,
        user: UserTest,
      },
      { name: "Tequila", quantity: 789, user: UserTest },
      { name: "Salsicha de porco", quantity: 945, user: UserTest },
      {
        name: "Suco de tangerina light",
        quantity: 895,
        user: UserTest,
      },
      {
        name: "Suco de beterraba orgânico light",
        quantity: 128,
        user: UserTest,
      },
      { name: "Milho", quantity: 713, user: UserTest },
      { name: "Ervilha", quantity: 352, user: UserTest },
      { name: "Suco de abacaxi", quantity: 477, user: UserTest },
      { name: "Batata-doce", quantity: 740, user: UserTest },
      { name: "Suco de amora", quantity: 391, user: UserTest },
      { name: "Alface", quantity: 114, user: UserTest },
      { name: "Chocolate com morango", quantity: 968, user: UserTest },
      { name: "Maionese", quantity: 528, user: UserTest },
      {
        name: "Suco de tangerina integral light",
        quantity: 545,
        user: UserTest,
      },
      {
        name: "Suco de beterraba light",
        quantity: 171,
        user: UserTest,
      },
      { name: "Suco de laranja", quantity: 41, user: UserTest },
      {
        name: "Suco de beterraba integral light",
        quantity: 966,
        user: UserTest,
      },
      { name: "Mortadela", quantity: 197, user: UserTest },
      { name: "Macarrão", quantity: 42, user: UserTest },
      {
        name: "Suco de tamarindo light",
        quantity: 772,
        user: UserTest,
      },
      { name: "Gelatina", quantity: 899, user: UserTest },
      {
        name: "Suco de graviola integral",
        quantity: 837,
        user: UserTest,
      },
      { name: "Suco de kiwi orgânico", quantity: 12, user: UserTest },
      { name: "Requeijão", quantity: 672, user: UserTest },
      { name: "Suco de graviola light", quantity: 741, user: UserTest },
      { name: "Saquê", quantity: 896, user: UserTest },
      { name: "Brócolis", quantity: 750, user: UserTest },
      { name: "Suco de cenoura", quantity: 661, user: UserTest },
      {
        name: "Suco de morango integral light",
        quantity: 201,
        user: UserTest,
      },
      {
        name: "Suco de morango orgânico",
        quantity: 560,
        user: UserTest,
      },
      { name: "Suco de cranberry", quantity: 968, user: UserTest },
      { name: "Limão", quantity: 332, user: UserTest },
      { name: "Suco de abacaxi", quantity: 917, user: UserTest },
      {
        name: "Suco de cranberry light",
        quantity: 339,
        user: UserTest,
      },
      { name: "Azeite", quantity: 655, user: UserTest },
      { name: "Chocolate com café", quantity: 236, user: UserTest },
      {
        name: "Suco de beterraba orgânico light",
        quantity: 408,
        user: UserTest,
      },
      { name: "Abóbora", quantity: 744, user: UserTest },
      {
        name: "Suco de tangerina orgânico light",
        quantity: 476,
        user: UserTest,
      },
      { name: "Suco de açaí", quantity: 59, user: UserTest },
      { name: "Suco de acerola light", quantity: 624, user: UserTest },
      { name: "Cachaça", quantity: 556, user: UserTest },
      { name: "Maçã", quantity: 580, user: UserTest },
      {
        name: "Suco de abóbora integral",
        quantity: 634,
        user: UserTest,
      },
      { name: "Geleia", quantity: 270, user: UserTest },
      {
        name: "Suco de maracujá integral",
        quantity: 102,
        user: UserTest,
      },
      { name: "Suco de graviola light", quantity: 787, user: UserTest },
      { name: "Suco de maracujá", quantity: 310, user: UserTest },
      {
        name: "Suco de laranja orgânico",
        quantity: 209,
        user: UserTest,
      },
      { name: "Alface", quantity: 107, user: UserTest },
      { name: "Suco de acerola light", quantity: 663, user: UserTest },
      { name: "Suco de coco", quantity: 288, user: UserTest },
      {
        name: "Suco de cranberry light",
        quantity: 956,
        user: UserTest,
      },
      {
        name: "Suco de coco integral light",
        quantity: 378,
        user: UserTest,
      },
      { name: "Molho barbecue", quantity: 798, user: UserTest },
      {
        name: "Suco de acerola orgânico",
        quantity: 506,
        user: UserTest,
      },
      { name: "Atum", quantity: 10, user: UserTest },
      { name: "Manga", quantity: 255, user: UserTest },
      { name: "Iogurte", quantity: 206, user: UserTest },
      {
        name: "Suco de açaí integral light",
        quantity: 390,
        user: UserTest,
      },
      { name: "Melão", quantity: 834, user: UserTest },
      {
        name: "Suco de pêssego orgânico light",
        quantity: 454,
        user: UserTest,
      },
      {
        name: "Suco de kiwi orgânico light",
        quantity: 328,
        user: UserTest,
      },
      { name: "Suco de caju", quantity: 434, user: UserTest },
      {
        name: "Suco de acerola integral light",
        quantity: 872,
        user: UserTest,
      },
      { name: "Salgadinho", quantity: 392, user: UserTest },
      {
        name: "Suco de abóbora orgânico",
        quantity: 489,
        user: UserTest,
      },
      { name: "Suco de uva integral", quantity: 489, user: UserTest },
      { name: "Suco de pêssego", quantity: 424, user: UserTest },
      { name: "Manteiga", quantity: 613, user: UserTest },
      { name: "Melão", quantity: 235, user: UserTest },
      { name: "Suco de goiaba light", quantity: 827, user: UserTest },
      {
        name: "Suco de tangerina orgânico light",
        quantity: 491,
        user: UserTest,
      },
      {
        name: "Suco de maracujá orgânico light",
        quantity: 388,
        user: UserTest,
      },
      { name: "Suco de limão", quantity: 306, user: UserTest },
      { name: "Suco de acerola", quantity: 970, user: UserTest },
      {
        name: "Suco de abacaxi integral light",
        quantity: 25,
        user: UserTest,
      },
      { name: "Leite", quantity: 167, user: UserTest },
      { name: "Suco de cranberry", quantity: 29, user: UserTest },
      { name: "Chocolate", quantity: 555, user: UserTest },
      { name: "Suco de morango", quantity: 221, user: UserTest },
      { name: "Suco de acerola diet", quantity: 930, user: UserTest },
      {
        name: "Suco de cranberry orgânico light",
        quantity: 199,
        user: UserTest,
      },
      {
        name: "Suco de tamarindo orgânico",
        quantity: 529,
        user: UserTest,
      },
      { name: "Geleia", quantity: 66, user: UserTest },
      { name: "Suco de pêssego diet", quantity: 26, user: UserTest },
      { name: "Lentilha", quantity: 516, user: UserTest },
      { name: "Castanha", quantity: 141, user: UserTest },
      {
        name: "Suco de cenoura integral light",
        quantity: 400,
        user: UserTest,
      },
      { name: "Salgadinho", quantity: 466, user: UserTest },
      { name: "Gelatina", quantity: 711, user: UserTest },
      { name: "Almôndega", quantity: 504, user: UserTest },
      {
        name: "Suco de cenoura integral",
        quantity: 804,
        user: UserTest,
      },
      { name: "Suco de goiaba light", quantity: 666, user: UserTest },
      { name: "Coco ralado", quantity: 640, user: UserTest },
      { name: "Suco de coco integral", quantity: 540, user: UserTest },
      { name: "Noz", quantity: 54, user: UserTest },
      { name: "Kiwi", quantity: 143, user: UserTest },
      {
        name: "Suco de maracujá orgânico",
        quantity: 616,
        user: UserTest,
      },
      {
        name: "Suco de cranberry integral",
        quantity: 24,
        user: UserTest,
      },
      { name: "Pêssego", quantity: 354, user: UserTest },
      { name: "Picles", quantity: 429, user: UserTest },
      { name: "Suco de melancia light", quantity: 977, user: UserTest },
      {
        name: "Suco de maracujá integral",
        quantity: 514,
        user: UserTest,
      },
      {
        name: "Suco de uva integral light",
        quantity: 379,
        user: UserTest,
      },
      { name: "Suco de tangerina diet", quantity: 736, user: UserTest },
      { name: "Chocolate com passas", quantity: 856, user: UserTest },
      {
        name: "Suco de limão orgânico light",
        quantity: 201,
        user: UserTest,
      },
      {
        name: "Suco de graviola orgânico light",
        quantity: 101,
        user: UserTest,
      },
      { name: "Suco de caju light", quantity: 412, user: UserTest },
      { name: "Molho barbecue", quantity: 597, user: UserTest },
      { name: "Chocolate com amêndoas", quantity: 936, user: UserTest },
      {
        name: "Suco de cenoura orgânico",
        quantity: 363,
        user: UserTest,
      },
      { name: "Vinagre", quantity: 261, user: UserTest },
      {
        name: "Suco de cenoura integral",
        quantity: 240,
        user: UserTest,
      },
      { name: "Ervilha", quantity: 164, user: UserTest },
      { name: "Gin", quantity: 493, user: UserTest },
      { name: "Queijo", quantity: 530, user: UserTest },
      { name: "Refrigerante", quantity: 662, user: UserTest },
      {
        name: "Suco de cranberry orgânico light",
        quantity: 238,
        user: UserTest,
      },
      { name: "Suco de goiaba light", quantity: 630, user: UserTest },
      {
        name: "Suco de maracujá orgânico light",
        quantity: 597,
        user: UserTest,
      },
      { name: "Molho barbecue", quantity: 467, user: UserTest },
      { name: "Suco de graviola light", quantity: 916, user: UserTest },
      { name: "Suco de pêssego", quantity: 957, user: UserTest },
      { name: "Carne", quantity: 986, user: UserTest },
      { name: "Molho barbecue", quantity: 345, user: UserTest },
      { name: "Presunto", quantity: 178, user: UserTest },
      { name: "Abacaxi", quantity: 490, user: UserTest },
      { name: "Chocolate com café", quantity: 434, user: UserTest },
      { name: "Queijo", quantity: 72, user: UserTest },
      { name: "Chocolate branco", quantity: 271, user: UserTest },
      { name: "Cereal", quantity: 306, user: UserTest },
      { name: "Suco de açaí light", quantity: 702, user: UserTest },
      { name: "Chocolate com caramelo", quantity: 719, user: UserTest },
      { name: "Suco de goiaba diet", quantity: 331, user: UserTest },
      { name: "Suco de laranja diet", quantity: 524, user: UserTest },
      { name: "Suco de tamarindo light", quantity: 69, user: UserTest },
      { name: "Leite condensado", quantity: 792, user: UserTest },
      { name: "Chocolate", quantity: 725, user: UserTest },
      {
        name: "Suco de abóbora integral",
        quantity: 724,
        user: UserTest,
      },
      { name: "Batata-doce", quantity: 411, user: UserTest },
      {
        name: "Suco de limão integral light",
        quantity: 428,
        user: UserTest,
      },
      {
        name: "Suco de abacaxi integral",
        quantity: 467,
        user: UserTest,
      },
      {
        name: "Suco de morango orgânico light",
        quantity: 714,
        user: UserTest,
      },
      { name: "Leite condensado", quantity: 366, user: UserTest },
      {
        name: "Suco de morango orgânico light",
        quantity: 86,
        user: UserTest,
      },
      { name: "Aveia", quantity: 736, user: UserTest },
      { name: "Leite condensado", quantity: 388, user: UserTest },
      { name: "Uva", quantity: 909, user: UserTest },
      {
        name: "Suco de tangerina orgânico light",
        quantity: 500,
        user: UserTest,
      },
      {
        name: "Suco de cenoura integral light",
        quantity: 582,
        user: UserTest,
      },
      { name: "Tequila", quantity: 539, user: UserTest },
      { name: "Tequila", quantity: 170, user: UserTest },
      { name: "Salsicha", quantity: 777, user: UserTest },
      {
        name: "Suco de abóbora orgânico light",
        quantity: 751,
        user: UserTest,
      },
      {
        name: "Suco de açaí integral light",
        quantity: 627,
        user: UserTest,
      },
      { name: "Ervilha", quantity: 882, user: UserTest },
      { name: "Suco de abóbora light", quantity: 343, user: UserTest },
      {
        name: "Suco de cranberry orgânico light",
        quantity: 779,
        user: UserTest,
      },
      { name: "Cream cheese", quantity: 204, user: UserTest },
      { name: "Iogurte", quantity: 819, user: UserTest },
      { name: "Suco de beterraba", quantity: 251, user: UserTest },
      {
        name: "Suco de melancia orgânico light",
        quantity: 616,
        user: UserTest,
      },
      {
        name: "Suco de graviola orgânico",
        quantity: 488,
        user: UserTest,
      },
      {
        name: "Suco de beterraba integral light",
        quantity: 382,
        user: UserTest,
      },
      { name: "Suco de açaí diet", quantity: 315, user: UserTest },
      {
        name: "Suco de tangerina light",
        quantity: 310,
        user: UserTest,
      },
      { name: "Suco de tamarindo", quantity: 829, user: UserTest },
      {
        name: "Suco de tamarindo integral light",
        quantity: 99,
        user: UserTest,
      },
      { name: "Licor", quantity: 47, user: UserTest },
      { name: "Suco de caju", quantity: 674, user: UserTest },
      { name: "Suco de melancia light", quantity: 222, user: UserTest },
      {
        name: "Suco de pêssego orgânico light",
        quantity: 313,
        user: UserTest,
      },
      { name: "Suco de limão orgânico", quantity: 818, user: UserTest },
      { name: "Rum", quantity: 848, user: UserTest },
      {
        name: "Suco de acerola orgânico light",
        quantity: 606,
        user: UserTest,
      },
      { name: "Suco de cenoura", quantity: 412, user: UserTest },
      { name: "Ketchup", quantity: 889, user: UserTest },
      {
        name: "Suco de laranja integral",
        quantity: 587,
        user: UserTest,
      },
      {
        name: "Suco de abóbora integral",
        quantity: 385,
        user: UserTest,
      },
      { name: "Suco de tangerina diet", quantity: 128, user: UserTest },
      { name: "Suco de abóbora diet", quantity: 100, user: UserTest },
      { name: "Chocolate com passas", quantity: 224, user: UserTest },
      {
        name: "Suco de goiaba orgânico light",
        quantity: 698,
        user: UserTest,
      },
      { name: "Suco de uva integral", quantity: 809, user: UserTest },
      { name: "Alho", quantity: 377, user: UserTest },
      { name: "Vodka", quantity: 197, user: UserTest },
      { name: "Chocolate com morango", quantity: 600, user: UserTest },
      { name: "Macarrão", quantity: 779, user: UserTest },
      {
        name: "Suco de goiaba orgânico light",
        quantity: 965,
        user: UserTest,
      },
      { name: "Suco de cenoura", quantity: 951, user: UserTest },
      {
        name: "Suco de beterraba orgânico",
        quantity: 165,
        user: UserTest,
      },
      {
        name: "Suco de abóbora orgânico",
        quantity: 674,
        user: UserTest,
      },
      { name: "Biscoito", quantity: 921, user: UserTest },
      {
        name: "Suco de melancia orgânico",
        quantity: 774,
        user: UserTest,
      },
      { name: "Alho", quantity: 580, user: UserTest },
      { name: "Suco de limão light", quantity: 343, user: UserTest },
      {
        name: "Suco de cenoura orgânico",
        quantity: 776,
        user: UserTest,
      },
      { name: "Vinho rosé", quantity: 63, user: UserTest },
      {
        name: "Suco de abóbora orgânico",
        quantity: 556,
        user: UserTest,
      },
      { name: "Suco de goiaba light", quantity: 434, user: UserTest },
      { name: "Suco de amora", quantity: 956, user: UserTest },
      { name: "Suco de goiaba light", quantity: 217, user: UserTest },
      {
        name: "Suco de tangerina integral",
        quantity: 186,
        user: UserTest,
      },
      { name: "Kiwi", quantity: 386, user: UserTest },
      { name: "Molho de soja", quantity: 918, user: UserTest },
      { name: "Creme de leite", quantity: 152, user: UserTest },
      { name: "Cream cheese", quantity: 328, user: UserTest },
      {
        name: "Suco de cenoura orgânico light",
        quantity: 119,
        user: UserTest,
      },
      { name: "Batata-doce", quantity: 62, user: UserTest },
      { name: "Uva", quantity: 583, user: UserTest },
      { name: "Alface", quantity: 493, user: UserTest },
      {
        name: "Suco de uva orgânico light",
        quantity: 702,
        user: UserTest,
      },
      {
        name: "Suco de goiaba integral",
        quantity: 385,
        user: UserTest,
      },
      { name: "Suco de cranberry diet", quantity: 113, user: UserTest },
      { name: "Pistache", quantity: 212, user: UserTest },
      { name: "Uva", quantity: 877, user: UserTest },
      { name: "Suco de açaí orgânico", quantity: 235, user: UserTest },
      { name: "Suco de laranja diet", quantity: 58, user: UserTest },
      { name: "Suco de morango", quantity: 788, user: UserTest },
      { name: "Licor", quantity: 359, user: UserTest },
      {
        name: "Suco de açaí integral light",
        quantity: 606,
        user: UserTest,
      },
      { name: "Doce de leite", quantity: 211, user: UserTest },
      { name: "Abóbora", quantity: 477, user: UserTest },
      {
        name: "Suco de cenoura integral",
        quantity: 765,
        user: UserTest,
      },
      { name: "Suco de acerola diet", quantity: 374, user: UserTest },
      { name: "Suco de coco orgânico", quantity: 564, user: UserTest },
      { name: "Suco de cenoura", quantity: 167, user: UserTest },
      {
        name: "Suco de pêssego orgânico light",
        quantity: 607,
        user: UserTest,
      },
      { name: "Suco de limão", quantity: 784, user: UserTest },
      { name: "Suco de kiwi integral", quantity: 442, user: UserTest },
      { name: "Cream cheese", quantity: 505, user: UserTest },
      {
        name: "Suco de maçã orgânico light",
        quantity: 656,
        user: UserTest,
      },
      {
        name: "Suco de kiwi integral light",
        quantity: 884,
        user: UserTest,
      },
      {
        name: "Suco de morango integral light",
        quantity: 542,
        user: UserTest,
      },
      {
        name: "Suco de maçã integral light",
        quantity: 340,
        user: UserTest,
      },
      {
        name: "Suco de morango orgânico",
        quantity: 587,
        user: UserTest,
      },
      { name: "Cereal", quantity: 478, user: UserTest },
      { name: "Chocolate com morango", quantity: 193, user: UserTest },
      {
        name: "Suco de graviola integral",
        quantity: 201,
        user: UserTest,
      },
      { name: "Pera", quantity: 558, user: UserTest },
      {
        name: "Suco de acerola orgânico light",
        quantity: 41,
        user: UserTest,
      },
      { name: "Cream cheese", quantity: 195, user: UserTest },
      { name: "Pera", quantity: 375, user: UserTest },
      {
        name: "Suco de cranberry light",
        quantity: 100,
        user: UserTest,
      },
      {
        name: "Suco de laranja orgânico light",
        quantity: 659,
        user: UserTest,
      },
      { name: "Chocolate com passas", quantity: 832, user: UserTest },
      { name: "Doce de leite", quantity: 389, user: UserTest },
      { name: "Sorvete", quantity: 36, user: UserTest },
      {
        name: "Suco de abacaxi integral light",
        quantity: 899,
        user: UserTest,
      },
      { name: "Suco de maçã orgânico", quantity: 559, user: UserTest },
      { name: "Brócolis", quantity: 258, user: UserTest },
      { name: "Chocolate com menta", quantity: 829, user: UserTest },
      { name: "Amêndoa", quantity: 75, user: UserTest },
      { name: "Pasta de amendoim", quantity: 478, user: UserTest },
      { name: "Mortadela", quantity: 979, user: UserTest },
      { name: "Chocolate com menta", quantity: 705, user: UserTest },
      { name: "Suco de melancia light", quantity: 365, user: UserTest },
      {
        name: "Suco de morango orgânico",
        quantity: 53,
        user: UserTest,
      },
    ];

    const newProduct = await repository.create(products);
    await repository.save(newProduct);
  }
}
